version: 0.1
phases:
  install:
    commands:
      - pip install -r ./LambdaCode/requirements.txt -t ./
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket bad-bots-code-bucket --output-template-file outputSamTemplate.yaml
      #- python -m pytest tests -sv

artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml